### PR TITLE
Update hulk.py

### PR DESCRIPTION
**Pull request by Tosible**
-Improved buildblock
-More randomizers
-More referrers
-Compressed and shortened the script slightly
-Minor changes

### CODE REVIEW

**Comment by m-messiah** [comment]
1. You broke PEP8 compability.
2. If you want to increase referers list - maybe It would be great extend it by all search engines, we know? Now - it is useful and I think it is not improvement.
3. When you generate block by choosing from your validChars, you can get such string as '23GtY3', for example, which, of course, is not valid param name, and may lead to undefined behavior. (Maybe simple decline that request, maybe Dos with simple filtration). 
4. I don't know, why you think choice from list with translating to char would be faster than choice from string. Do you have any proves? Moreover, your code won't work on Python3.

+5. Cache-control - good idea. Maybe it would be helpful

**Comment by Tosible** [comment]
Sorry, I'm used to Python 2.x, never used Python 3.x. Also, I'm quite new to programming, so I don't know what PEP8 compatibility is.

The buildblock I changed was for the referers, I should have made another for the params. My bad.

I will redo and fix the mistakes.

Also, is there a way to bypass Cookie authentication? It will make your script harder to mitigate.

**Comment by m-messiah** [comment]
[PEP8](https://www.python.org/dev/peps/pep-0008/) is a de-facto standard of clean and beautiful Python code.

Now, when I rewrite it by using requests library - Cookie authentication appears and you can simply implement it. Or, if I will have some more time - I will add it to script.

**Comment by Tosible** [comment]
I redid the script. I added a referer generator, but it's limited to ".com" domains. 
I also renamed "buildblock" to "buildblocks", and added your original "buildblock".

**Comment by Tosible** [comment]
Along with the cookie authentication bypass, do you think you can implement the randomization of headers? It's one of the ways the original HULK got mitigated.

**Pull request merged**
